# -*- coding: utf-8 -*-
"""SimuladorChurrascoPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPIhVhxtbLJut3ZARM3vA-AWb0WaF5eG
"""

qtdCarvao = 1 # 1 pacote para cada 10 pessoas

qtdCarneHomem = 0.4
qtdFrangoHomem = 0.2
qtdCervejaHomem = 4 # Homem bebe 4 latas de cerveja
qtdRefriHomem = 0.25 # 500 ml de refrigerante

precoCarneHomem = 50.0 #k g do contra filé
precoFrangoHomem = 23.0 # kg de tulipa
precoCervejaHomem = 3.99 # lata heineken 269ml
precoRefriHomem = 8.0 # garrafa de 2 litroS




qtdCarneMulher= 0.2
qtdFrangoMulher = 0.2
qtdCervejaMulher = 2 # Homem bebe 4 latas de cerveja
qtdRefriMulher = 0.15 # 500 ml de refrigerante

precoCarneMulher = 50.0 #kg do contra filé
precoFrangoMulher = 23.0 # kg de tulipa
precoCervejaMulher = 3.99 # lata heineken 269ml
precoRefriMulher = 8.0 # garrafa de 2 litros




qtdCarneCrianca= 0.4
qtdFrangoCrianca = 0.2
qtdRefriCrianca= 0.25 # 500 ml de refrigerante

precoCarneCrianca = 50.0 #k g do contra filé
precoFrangoCrianca = 23.0 # kg de tulipa
precoRefriCrianca = 8.0 # garrafa de 2 litros



#Capturar as informações
print('*****Bem-Vindos a calculadora do seu churrasco*****')
print()
homens = float(input('Quantos homens haverão nesse churrasco? '))
print()
mulheres = float(input('Quantas mulheres haverão nesse churrasco? '))
print()
criancas = float(input('Quantas crianças haverão nesse churrasco? '))
print()

#Cálculo de peso

carneHomem = homens * qtdCarneHomem
carneMulher = mulheres * qtdCarneMulher
carneCrianca = criancas * qtdCarneCrianca

frangoHomem = homens * qtdFrangoHomem
frangoMulher = mulheres * qtdFrangoMulher
frangoCrianca = criancas * qtdFrangoCrianca

refriHomem = homens * qtdRefriHomem
refriMulher = mulheres * qtdRefriMulher
refriCrianca = criancas * qtdRefriCrianca

cervejaHomem = homens * qtdCervejaHomem
cervejaMulher = mulheres * qtdCervejaMulher

carvao = (homens + mulheres + criancas) / 10

#Criar os cálculos de gastos

valorCarneHomem = carneHomem * precoCarneHomem
valorFrangoHomem = frangoHomem * precoFrangoHomem
valorCervejaHomem = cervejaHomem * precoCervejaHomem
valorRefriHomem = refriHomem * precoRefriHomem

preco_Total_Homem = valorCarneHomem + valorFrangoHomem + valorCervejaHomem + valorRefriHomem

valorCarneMulher = carneMulher * precoCarneMulher
valorFrangoMulher = frangoMulher * precoFrangoMulher
valorCervejaMulher = cervejaMulher * precoCervejaMulher
valorRefriMulher = refriMulher * precoRefriMulher

preco_Total_Mulher = valorCarneMulher + valorFrangoMulher + valorCervejaMulher + valorRefriMulher

valorCarneCrianca = carneCrianca * precoCarneCrianca
valorFrangoCrianca = frangoCrianca * precoFrangoCrianca
valorRefriCrianca = refriCrianca * precoRefriCrianca

preco_Total_Crianca = valorCarneCrianca + valorFrangoCrianca + valorRefriCrianca


valor_Total = preco_Total_Homem + preco_Total_Mulher + preco_Total_Crianca

#Imprimir os resultados

print(f'Total de Homens: {homens}')
print(f'Total de Mulheres: {mulheres}')
print(f'Total de Crianças: {criancas}')
print()
print(f'Lista de Compras: {carneHomem + carneMulher + carneCrianca:.2f} kgs de Carne')
print(f'                  {frangoHomem + frangoMulher + frangoCrianca:.2f} kgs de Frango')
print(f'                  {refriHomem + refriMulher + refriCrianca:.2f} litros de Refrigerante')
print(f'                 - {cervejaHomem + cervejaMulher:.2f} latas de Cerveja')
print(f'                  {carvao} pacotes de Carvão')

# Mostrar valores
print()
print(f'Valor total da compra: R${valor_Total:.2f}')
print()
print(f'Valor da vaquinha por pessoa: R${valor_Total / (homens + mulheres + criancas):.2f}')